"""empty message

Revision ID: 1d246a994c86
Revises: 56d81e69174b
Create Date: 2024-12-04 23:22:12.056636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d246a994c86'
down_revision = '56d81e69174b'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column(
            'homeworld',
            existing_type=sa.String(),
            type_=sa.Integer(),
            postgresql_using="homeworld::integer"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residents', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('homeworld',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    op.drop_table('favorite_planet')
    # ### end Alembic commands ###
