"""empty message

Revision ID: 2686a812ed4b
Revises: 1d246a994c86
Create Date: 2024-12-17 22:12:23.442515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2686a812ed4b'
down_revision = '1d246a994c86'
branch_labels = None
depends_on = None


def upgrade():
    # Eliminar la tabla 'people' y todas sus dependencias
    op.execute("DROP TABLE people CASCADE")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('token')
        batch_op.drop_column('username')
        batch_op.drop_column('age')
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residents', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('planets_name_key', ['name'])

    op.create_table('favorite_person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name='favorite_person_person_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_person_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_person_pkey')
    )
    op.create_table('people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mass', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hair_color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('skin_color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('eye_color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('birth_year', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('homeworld', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='people_pkey'),
    sa.UniqueConstraint('name', name='people_name_key')
    )
    op.drop_table('favorite_people')
    op.drop_table('favorite_planets')
    op.drop_table('characters')
    # ### end Alembic commands ###
