"""empty message

Revision ID: 56d81e69174b
Revises: 85b138bd2d1d
Create Date: 2024-12-04 21:34:27.080021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d81e69174b'
down_revision = '85b138bd2d1d'
branch_labels = None
depends_on = None


def upgrade():
    # Elimina la restricción de clave foránea en favorite_person
    op.drop_constraint('favorite_person_person_id_fkey', 'favorite_person', type_='foreignkey')

    # Ahora elimina la tabla 'people'
    op.drop_table('people')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('rotation_period', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('orbital_period', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('diameter', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('climate', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('gravity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('terrain', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('surface_water', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('population', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('residents', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='planet_pkey'),
    sa.UniqueConstraint('name', name='planet_name_key')
    )
    op.drop_table('planets')
    # ### end Alembic commands ###
